face_cascade_path = 'haarcascades/haarcascade_frontalface_default.xml'
eye_cascade_path = 'haarcascades/haarcascade_eye_tree_eyeglasses.xml'
sound_path = 'sound/alarm-clock.wav'
logs_path = 'logs/'
checksum_path = 'checksums/'